### ISSUE TITLE
Can't connect Firefly-III account

### ISSUE THREAD

**Issue by opiumcloud** [vjFaLk/firefly-bot#4]
Hi!

I'm having issues connecting the botu to the Firefly account. Whe I type the user token, the bot answers nothing in the chat. The log displays the folowwing at that moment: "[...] caused error 'Expecting value: line 1 column 1 (char 0)'".

How can I solve this? Thanks in advance!

**Comment by evanre** [comment]
Hello there, I've faced the same issue. @vjFaLk any ideas how to fix it?

**Comment by vjFaLk** [comment]
@evanre @opiumcloud Sorry for the late reply! There's a really silly bug that I keep forgetting to fix. Make sure that when you set the URL for your Firefly instance you don't include a trailing slash. I think you might have to delete the bot-data file and start over. Let me know if that works.

**Comment by vjFaLk** [comment]
Update : I've fixed the issue where a trailing slash would break the bot, but you will probably have to delete the "bot-data" file in the config folder and start over.

**Comment by evanre** [comment]
Hi, @vjFaLk, thanks for quick response =) I'm still getting the error (I've cloned the repo and built image from the Dockerfile). The domain I sent to bot chat looks like this: "https://money.mywebsite.com". Error appears when I send access token to it. Here's full error dump
```
2021-01-30T10:50:37.707015610Z /usr/local/lib/python3.8/site-packages/telegram/ext/conversationhandler.py:220: UserWarning: If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2021-01-30T10:50:37.707103173Z   warnings.warn("If 'per_message=False', 'CallbackQueryHandler' will not be "
2021-01-30T10:50:37.707207114Z 2021-01-30 10:50:37,706 - __main__ - WARNING - Update '{'update_id': 916579035, 'message': {'message_id': 28, 'date': 1612003837, 'chat': {'id': 3***6, 'type': 'private', 'username': '****', 'first_name': '****', 'last_name': '****'}, 'text': 'vsC**********AnQW', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 3*****016, 'first_name': '*****', 'is_bot': False, 'last_name': '*****', 'username': '****', 'language_code': 'en'}}}' caused error 'Expecting value: line 1 column 1 (char 0)'
```

**Comment by vjFaLk** [comment]
@evanre The domain should look like a full URL. So instead of "money.mywebsite.com" it should be "https://money.mywebsite.com" (Doesn't need to be HTTPS, just include the protocol in there)

If you're mounting the config directory, make sure to delete the "bot-data" file before trying again. 

I need to have a better way of handling failures.

**Comment by evanre** [comment]
@vjFaLk that's exactly what I've sent to chat - "https://money.mywebsite.com". "bot-data" is also presented in mounted dir. I'm not familiar with Python, but it looks like the problem with reading json response.

**Comment by vjFaLk** [comment]
Oh Github changes the way the URL looks 🤦‍♂️. Did you try deleting the bot-data file and restarting? 

I was able to reproduce the error, and also the fix by deleting the bot-data file and restarting.

**Comment by evanre** [comment]
@vjFaLk No luck, tried on two different servers. With both: basic image `vjfalk1/firefly-telegram-bot` and building manually from repo. Could you dm me in telegram (the same as github's nickname)? I'll provide all the configs with personal info.

**Comment by evanre** [comment]
I've found what was the problem, I was trying to provide an OAuth Client token instead of Personal Access Token.

**Comment by vjFaLk** [comment]
Hey @evanre I'm sorry I was able to help you out earlier, it's been hectic. But I'm glad you figured it out 👍
